---
- name: Install Python (Debian)
  raw: sudo apt-get install -y python
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install prerequisites (CentOS)
  yum:
    name:
      - openssl-devel
      - pam-devel
      - libtool
      - autoconf
      - git
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  become: true

- name: Install prerequisites (Debian)
  apt:
    name:
      - libssl-dev
      - libpam-dev
      - libtool
      - autoconf
      - build-essential
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true

- name: Download duo
  git:
    dest: /tmp/duo
    repo: https://github.com/duosecurity/duo_unix.git
    force: yes
    accept_hostkey: yes
    version: master

- name: Generate duo configure
  command: autoreconf -i chdir=/tmp/duo

- name: Configure duo source
  command: ./configure --prefix=/usr --with-pam chdir=/tmp/duo

- name: Build duo
  command: make chdir=/tmp/duo

- name: Install duo
  command: make install chdir=/tmp/duo
  become: true

#- name: Clear duo source dir
#  file:
#    path: /tmp/duo
#    state: absent

- name: Install duo config
  template:
    src: login_duo.conf.j2
    dest: /etc/duo/login_duo.conf
    owner: sshd
    group: 0
    mode: 0600
  become: true

- name: Change requesite to sufficient
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: "auth sufficient pam_ldap.so try_first_pass"
    line: "auth requisite pam_ldap.so try_first_pass"
    backrefs: yes
  become: yes

- name: Install pam_duo module
  lineinfile:
    path: /etc/pam.d/sshd
    insertbefore: "auth required pam_deny.so"
    line: "auth sufficient /lib64/security/pam_duo.so"
  become: true

- name: Remove common-auth
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: "[^#]@include common-auth"
    line: "#@include common-auth"

- name: Restart ssh
  service: name=sshd state=restarted
  become: true
